version: '3.8'

services:
  backend:
    build: ./ch04
    container_name: backend
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - ./compose_data/backend/.env

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=gdsc
    volumes:
      - ./compose_data/postgres:/var/lib/postgresql/data

  frontend:
    build: ./ch03
    container_name: frontend
    ports:
      - 3000:3000
