FROM ubuntu:22.04

# 386MB
RUN apt-get update \
 && apt-get install -y vim build-essential \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# 426MB
RUN apt-get update
RUN apt-get install -y vim build-essential
# RUN apt-get clean
# RUN rm -rf /var/lib/apt/lists/*

# 426MB
RUN apt-get update
RUN apt-get install -y vim build-essential
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
